name: wrestle_predict
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '3.19.6'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.3
  provider: ^6.1.2
  get: ^4.6.6
  collection: ^1.18.0
  uuid: ^4.4.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - images/
    - images/wrestle_predict_logo.png
    - images/wrestle_predict_logo_1920_500.png
    - images/wrestle_predict_logo_1920_300.png

  uses-material-design: true
